name: Linting, testing, building
on: 
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
        - uses: actions/checkout@v2
        - name: Starting Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: install modules
          run: npm install
        - name: build production
          run: npm run build:prod
          if: always()
        - name: linting typescript
          if: always()
          run: npm run lint:ts
        - name: linting scss
          if: always()
          run: npm run lint:scss
        - name: Unit testing
          if: always()
          run: npm run unit
        - name: building storybook
          if: always()
          run: npm run build-storybook
        - name: screenshot testing  
          run: npm run loki:ci
         